const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
const FETCH_PRODUCT_SUCCESS="FETCH_PRODUCT_SUCCESS"
export { FETCH_PRODUCT_REQUEST, FETCH_PRODUCT_ERROR ,FETCH_PRODUCT_SUCCESS};
